### ISSUE TITLE
Why new model is initialized for Snapshot Ensemble

### ISSUE THREAD

**Issue by amitchandak** [SamsungLabs/pytorch-ensembles#6]
Hi,
Thanks for providing the code and your great work.
I was wondering why you are creating a new instance of the model in case of Snapshot ensemble ? 
Should we not just continue training the same model ? 
https://github.com/SamsungLabs/pytorch-ensembles/blob/76b71c9ea3886e3a7fece9ddc3740e26f64ecbaa/train/cifar/sse_mcmc_train.py#L195

Also in the shell script :
 https://github.com/SamsungLabs/pytorch-ensembles/blob/76b71c9ea3886e3a7fece9ddc3740e26f64ecbaa/train/train_sse_mcmc.sh#L8
I think it should be "$6" instead of "$3" .

Thank you

**Comment by alexlyzhov** [comment]
Hey @amitchandak,
Line 195: it's only run once at the beginning (see `if` above it).
Line 8: I think you're right, thanks for noticing. @senya-ashukha do you have write access to merge pull request by any chance? :)

**Comment by amitchandak** [comment]
Thank you, got your point
